### ISSUE TITLE
CaseClauseError raised when giving an invalid argument to a subcommand

### ISSUE THREAD

**Issue by ivan** [funbox/optimus#2]
Optimus raises `CaseClauseError` when passing unrecognized arguments to a subcommand:

```
# ./machine_manager help add
Machine Manager
Add a machine

USAGE:
    machine_manager add --hostname HOSTNAME --ip IP --ssh-port SSH_PORT [--tag TAG]

OPTIONS:

    -h, --hostname                                                              
    -i, --ip                                                                    
    -p, --ssh-port                                                              
    -t, --tag                                                                   

# ./machine_manager add asdf
** (CaseClauseError) no case clause matching: {:error, [:add], ["unrecognized arguments: \"asdf\""]}
    (optimus) lib/optimus.ex:96: Optimus.parse!/2
    (machine_manager) lib/machine_manager.ex:50: MachineManager.CLI.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

The corresponding code is:

```elixir
defmodule MachineManager.CLI do
  def main(opts) do
    spec = Optimus.new!(
      name:               "machine_manager",
      description:        "Machine Manager",
      about:              "Manages metadata about machines and probes them",
      allow_unknown_args: false,
      parse_double_dash:  true,
      subcommands: [
        add: [
          name:  "add",
          about: "Add a machine",
          options: [
            hostname: [
              short:    "-h",
              long:     "--hostname",
              required: true,
            ],
            ip: [
              short:    "-i",
              long:     "--ip",
              required: true,
            ],
            ssh_port: [
              short:    "-p",
              long:     "--ssh-port",
              required: true,
              parser:   :integer,
            ],
            tag: [
              short:    "-t",
              long:     "--tag",
              multiple: true,
            ],
          ]
        ]
      ]
    )
    options = Optimus.parse!(spec, opts)
    IO.inspect(options)
  end
end
```

**Comment by savonarola** [comment]
Hello!

Thanks for the feedback. Tried to fix this and add some test cases in the corresponding commit.
